# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"5\n\x0f\x41\x64\x64itionRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"\"\n\x10\x41\x64\x64itionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"9\n\x13SubstractionRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"&\n\x14SubstractionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\";\n\x15MultiplicationRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"(\n\x16MultiplicationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"4\n\x0f\x44ivisionRequest\x12\x0f\n\x07\x64ivisor\x18\x01 \x01(\x02\x12\x10\n\x08\x64ividend\x18\x02 \x01(\x02\"5\n\x10\x44ivisionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x11\n\tremainder\x18\x02 \x01(\x05\"1\n\x12\x45xponentialRequest\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\r\n\x05power\x18\x02 \x01(\x05\"%\n\x13\x45xponentialResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x96\x03\n\nCalculator\x12\x45\n\x08\x61\x64\x64ition\x12\x1b.calculator.AdditionRequest\x1a\x1c.calculator.AdditionResponse\x12Q\n\x0csubstraction\x12\x1f.calculator.SubstractionRequest\x1a .calculator.SubstractionResponse\x12W\n\x0emultiplication\x12!.calculator.MultiplicationRequest\x1a\".calculator.MultiplicationResponse\x12\x45\n\x08\x64ivision\x12\x1b.calculator.DivisionRequest\x1a\x1c.calculator.DivisionResponse\x12N\n\x0b\x65xponential\x12\x1e.calculator.ExponentialRequest\x1a\x1f.calculator.ExponentialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDITIONREQUEST']._serialized_start=32
  _globals['_ADDITIONREQUEST']._serialized_end=85
  _globals['_ADDITIONRESPONSE']._serialized_start=87
  _globals['_ADDITIONRESPONSE']._serialized_end=121
  _globals['_SUBSTRACTIONREQUEST']._serialized_start=123
  _globals['_SUBSTRACTIONREQUEST']._serialized_end=180
  _globals['_SUBSTRACTIONRESPONSE']._serialized_start=182
  _globals['_SUBSTRACTIONRESPONSE']._serialized_end=220
  _globals['_MULTIPLICATIONREQUEST']._serialized_start=222
  _globals['_MULTIPLICATIONREQUEST']._serialized_end=281
  _globals['_MULTIPLICATIONRESPONSE']._serialized_start=283
  _globals['_MULTIPLICATIONRESPONSE']._serialized_end=323
  _globals['_DIVISIONREQUEST']._serialized_start=325
  _globals['_DIVISIONREQUEST']._serialized_end=377
  _globals['_DIVISIONRESPONSE']._serialized_start=379
  _globals['_DIVISIONRESPONSE']._serialized_end=432
  _globals['_EXPONENTIALREQUEST']._serialized_start=434
  _globals['_EXPONENTIALREQUEST']._serialized_end=483
  _globals['_EXPONENTIALRESPONSE']._serialized_start=485
  _globals['_EXPONENTIALRESPONSE']._serialized_end=522
  _globals['_CALCULATOR']._serialized_start=525
  _globals['_CALCULATOR']._serialized_end=931
# @@protoc_insertion_point(module_scope)
